from openai import OpenAI

# Set your API key here
API_KEY = ""

# Initialize the OpenAI client with the provided API key
client = OpenAI(api_key=API_KEY)

class Chat:
    def __init__(self):
        # Initialize a private variable to store the content of the response
        self.__content__ = None

    def response(self, prompt):
        """
        Generate a response from the OpenAI model based on the provided prompt.

        Args:
            prompt (str): The input text to which the model will respond.

        Returns:
            None: The result is stored in the instance variable __content__.
        """
        # Create a completion request to the OpenAI API using the provided model and prompt
        completion = client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[
                {
                    "role": "user",
                    "content": prompt,
                },
            ],
        )
        # Store the response content in the private instance variable
        self.__content__ = completion.choices[0].message.content.strip()

    def get_result(self):
        """
        Retrieve the stored response content.

        Returns:
            str: The content of the response generated by the model.
        """
        return self.__content__

